export const fakeClientData = {
  profile: {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@email.com',
    phone: '+351 912 345 678',
    dateOfBirth: '1989-03-15',
    address: 'Rua das Flores, 123, 1200-100 Lisboa',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    bloodType: 'A+',
    allergies: 'Penicilina, Pollen',
  },
  upcomingAppointments: [
    {
      id: '1',
      date: '2025-10-08',
      time: '14:30',
      practitioner: 'Dr. Maria Santos',
      specialty: 'Cardiologie',
      location: 'Cabinet Médical Central, Lisboa',
      type: 'Présentiel',
      status: 'confirmed',
      avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '2',
      date: '2025-10-12',
      time: '10:00',
      practitioner: 'Dr. Pedro Costa',
      specialty: 'Dentiste',
      location: 'Clinique Dentaire Moderne, Porto',
      type: 'Présentiel',
      status: 'confirmed',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '3',
      date: '2025-10-18',
      time: '16:00',
      practitioner: 'Dr. Ana Ferreira',
      specialty: 'Dermatologie',
      location: 'Téléconsultation',
      type: 'En ligne',
      status: 'pending',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
  ],
  pastAppointments: [
    {
      id: '4',
      date: '2025-09-20',
      time: '09:00',
      practitioner: 'Dr. Carlos Oliveira',
      specialty: 'Médecine Générale',
      location: 'Centre de Santé, Lisboa',
      type: 'Présentiel',
      status: 'completed',
      avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '5',
      date: '2025-08-15',
      time: '11:30',
      practitioner: 'Dr. Sofia Rodrigues',
      specialty: 'Ophtalmologie',
      location: 'Clinique des Yeux, Porto',
      type: 'Présentiel',
      status: 'completed',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '6',
      date: '2025-07-10',
      time: '15:00',
      practitioner: 'Dr. João Mendes',
      specialty: 'Kinésithérapie',
      location: 'Cabinet Kiné Plus, Lisboa',
      type: 'Présentiel',
      status: 'completed',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '7',
      date: '2025-06-05',
      time: '08:30',
      practitioner: 'Dr. Luisa Martins',
      specialty: 'Psychologie',
      location: 'Téléconsultation',
      type: 'En ligne',
      status: 'completed',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
    {
      id: '8',
      date: '2025-05-22',
      time: '13:00',
      practitioner: 'Dr. Ricardo Alves',
      specialty: 'Orthopédie',
      location: 'Hôpital São José, Lisboa',
      type: 'Présentiel',
      status: 'completed',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
  ],
  cancelledAppointments: [
    {
      id: '9',
      date: '2025-09-10',
      time: '10:30',
      practitioner: 'Dr. Teresa Lima',
      specialty: 'Nutrition',
      location: 'Cabinet Nutrition Santé, Lisboa',
      type: 'Présentiel',
      status: 'cancelled',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
    },
  ],
  documents: [
    {
      id: '1',
      name: 'Ordonnance - Dr. Santos',
      date: '2025-09-20',
      type: 'Ordonnance',
      practitioner: 'Dr. Carlos Oliveira',
      size: '245 KB',
    },
    {
      id: '2',
      name: 'Résultats analyse sanguine',
      date: '2025-08-10',
      type: 'Résultats analyses',
      practitioner: 'Laboratoire Central',
      size: '512 KB',
    },
    {
      id: '3',
      name: 'Radiographie genou droit',
      date: '2025-07-15',
      type: 'Imagerie',
      practitioner: 'Dr. Ricardo Alves',
      size: '2.1 MB',
    },
    {
      id: '4',
      name: 'Compte-rendu consultation',
      date: '2025-06-05',
      type: 'Autres',
      practitioner: 'Dr. Luisa Martins',
      size: '180 KB',
    },
  ],
  messages: [
    {
      id: '1',
      practitioner: 'Dr. Maria Santos',
      avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastMessage: 'Bonjour, je confirme votre rendez-vous du 8 octobre.',
      timestamp: '2025-10-02T10:30:00',
      unread: 1,
    },
    {
      id: '2',
      practitioner: 'Dr. Pedro Costa',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastMessage: 'N\'oubliez pas de ne pas manger 2h avant votre rendez-vous.',
      timestamp: '2025-10-01T14:20:00',
      unread: 0,
    },
  ],
  favoritePractitioners: [
    {
      id: '1',
      name: 'Dr. Maria Santos',
      specialty: 'Cardiologie',
      rating: 4.9,
      location: 'Lisboa',
      avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-15',
    },
    {
      id: '2',
      name: 'Dr. Pedro Costa',
      specialty: 'Dentiste',
      rating: 4.8,
      location: 'Porto',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-20',
    },
    {
      id: '3',
      name: 'Dr. Carlos Oliveira',
      specialty: 'Médecine Générale',
      rating: 4.7,
      location: 'Lisboa',
      avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-10',
    },
  ],
  searchResults: [
    {
      id: '1',
      name: 'Dr. Isabel Cardoso',
      specialty: 'Pédiatrie',
      rating: 4.9,
      reviews: 156,
      location: 'Av. da Liberdade, Lisboa',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-06',
      consultationType: ['Présentiel', 'En ligne'],
      price: '60€',
    },
    {
      id: '2',
      name: 'Dr. Miguel Torres',
      specialty: 'Psychiatrie',
      rating: 4.8,
      reviews: 203,
      location: 'Rua do Ouro, Porto',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-07',
      consultationType: ['En ligne'],
      price: '80€',
    },
    {
      id: '3',
      name: 'Dr. Beatriz Cunha',
      specialty: 'Gynécologie',
      rating: 4.9,
      reviews: 178,
      location: 'Praça do Comércio, Lisboa',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-09',
      consultationType: ['Présentiel'],
      price: '70€',
    },
    {
      id: '4',
      name: 'Dr. Rui Ferreira',
      specialty: 'Rhumatologie',
      rating: 4.7,
      reviews: 89,
      location: 'Avenida Boavista, Porto',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-11',
      consultationType: ['Présentiel', 'En ligne'],
      price: '65€',
    },
    {
      id: '5',
      name: 'Dr. Catarina Sousa',
      specialty: 'Endocrinologie',
      rating: 4.8,
      reviews: 134,
      location: 'Rua Garrett, Lisboa',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-08',
      consultationType: ['Présentiel', 'En ligne'],
      price: '75€',
    },
    {
      id: '6',
      name: 'Dr. André Lopes',
      specialty: 'Urologie',
      rating: 4.6,
      reviews: 92,
      location: 'Rua de Santa Catarina, Porto',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-13',
      consultationType: ['Présentiel'],
      price: '70€',
    },
  ],
  aiRecommendations: [
    {
      id: '1',
      specialty: 'Ophtalmologie',
      reason: 'Dernier examen il y a plus d\'un an',
      priority: 'medium',
    },
    {
      id: '2',
      specialty: 'Dentiste',
      reason: 'Contrôle annuel recommandé',
      priority: 'low',
    },
  ],
};

export const fakePatientData = {
  profile: {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@email.com',
    phone: '+351 912 345 678',
    dateOfBirth: '1989-03-15',
    address: 'Rua das Flores, 123, 1200-100 Lisboa',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    bloodType: 'A+',
    allergies: ['Penicilline', 'Pollen'],
    emergencyContact: {
      name: 'Maria Silva',
      phone: '+351 912 987 654',
      relationship: 'Épouse',
    },
  },
  upcomingAppointments: [
    {
      id: '1',
      date: '2025-10-08',
      time: '14:30',
      practitioner: {
        name: 'Dr. Maria Santos',
        specialty: 'Cardiologie',
        photo: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      location: 'Cabinet Médical Central, Lisboa',
      type: 'Présentiel',
      status: 'confirmed',
    },
    {
      id: '2',
      date: '2025-10-12',
      time: '10:00',
      practitioner: {
        name: 'Dr. Pedro Costa',
        specialty: 'Dentiste',
        photo: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      location: 'Clinique Dentaire Moderne, Porto',
      type: 'Présentiel',
      status: 'confirmed',
    },
  ],
  pastAppointments: [
    {
      id: '3',
      date: '2025-09-20',
      time: '09:00',
      practitioner: {
        name: 'Dr. Carlos Oliveira',
        specialty: 'Médecine Générale',
        photo: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      location: 'Centre de Santé, Lisboa',
      type: 'Présentiel',
      status: 'completed',
    },
    {
      id: '4',
      date: '2025-08-15',
      time: '11:30',
      practitioner: {
        name: 'Dr. Sofia Rodrigues',
        specialty: 'Ophtalmologie',
        photo: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      location: 'Clinique des Yeux, Porto',
      type: 'Présentiel',
      status: 'completed',
    },
  ],
  documents: [
    {
      id: '1',
      name: 'Ordonnance - Dr. Santos',
      date: '2025-09-20',
      type: 'prescription',
      practitioner: 'Dr. Carlos Oliveira',
      size: '245 KB',
    },
    {
      id: '2',
      name: 'Résultats analyse sanguine',
      date: '2025-08-10',
      type: 'lab-results',
      practitioner: 'Laboratoire Central',
      size: '512 KB',
    },
    {
      id: '3',
      name: 'Radiographie genou droit',
      date: '2025-07-15',
      type: 'imaging',
      practitioner: 'Dr. Ricardo Alves',
      size: '2.1 MB',
    },
  ],
  messages: [
    {
      id: '1',
      practitioner: {
        name: 'Dr. Maria Santos',
        specialty: 'Cardiologie',
        photo: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      lastMessage: 'Bonjour, je confirme votre rendez-vous du 8 octobre.',
      timestamp: '2025-10-02T10:30:00',
      unread: 1,
    },
    {
      id: '2',
      practitioner: {
        name: 'Dr. Pedro Costa',
        specialty: 'Dentiste',
        photo: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      lastMessage: 'N\'oubliez pas de ne pas manger 2h avant votre rendez-vous.',
      timestamp: '2025-10-01T14:20:00',
      unread: 0,
    },
  ],
  favoritePractitioners: [
    {
      id: '1',
      name: 'Dr. Maria Santos',
      specialty: 'Cardiologie',
      rating: 4.9,
      address: 'Lisboa',
      photo: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-15',
    },
    {
      id: '2',
      name: 'Dr. Pedro Costa',
      specialty: 'Dentiste',
      rating: 4.8,
      address: 'Porto',
      photo: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-20',
    },
    {
      id: '3',
      name: 'Dr. Carlos Oliveira',
      specialty: 'Médecine Générale',
      rating: 4.7,
      address: 'Lisboa',
      photo: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-10',
    },
  ],
  searchResults: [
    {
      id: '1',
      name: 'Dr. Isabel Cardoso',
      specialty: 'Pédiatrie',
      rating: 4.9,
      reviews: 156,
      address: 'Av. da Liberdade, Lisboa',
      photo: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-06',
      consultationType: ['Présentiel', 'En ligne'],
      price: '60€',
    },
    {
      id: '2',
      name: 'Dr. Miguel Torres',
      specialty: 'Psychiatrie',
      rating: 4.8,
      reviews: 203,
      address: 'Rua do Ouro, Porto',
      photo: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-07',
      consultationType: ['En ligne'],
      price: '80€',
    },
    {
      id: '3',
      name: 'Dr. Beatriz Cunha',
      specialty: 'Gynécologie',
      rating: 4.9,
      reviews: 178,
      address: 'Praça do Comércio, Lisboa',
      photo: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-09',
      consultationType: ['Présentiel'],
      price: '70€',
    },
    {
      id: '4',
      name: 'Dr. Rui Ferreira',
      specialty: 'Rhumatologie',
      rating: 4.7,
      reviews: 89,
      address: 'Avenida Boavista, Porto',
      photo: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
      nextAvailable: '2025-10-11',
      consultationType: ['Présentiel', 'En ligne'],
      price: '65€',
    },
  ],
};

export const fakeProfessionalData = {
  profile: {
    id: '1',
    name: 'Dr. Maria Santos',
    specialty: 'Médecin généraliste',
    registrationNumber: 'OM-45892',
    email: 'maria.santos@cabinet.pt',
    phone: '+351 223 456 789',
    address: 'Rua de Santa Catarina, 350, 4000-124 Porto',
    avatar: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
    bio: 'Médecin généraliste avec 15 ans d\'expérience. Spécialisée dans la médecine préventive et le suivi des maladies chroniques.',
    languages: ['Portugais', 'Français', 'Anglais'],
    officeHours: {
      monday: '09:00-18:00',
      tuesday: '09:00-18:00',
      wednesday: '09:00-13:00',
      thursday: '09:00-18:00',
      friday: '09:00-17:00',
      saturday: 'Fermé',
      sunday: 'Fermé',
    },
  },
  kpis: {
    appointmentsToday: 8,
    appointmentsThisWeek: 34,
    attendanceRate: 92,
    monthlyRevenue: 5400,
    totalPatients: 25,
    totalAppointmentsThisMonth: 120,
  },
  todayAppointments: [
    {
      id: '1',
      time: '09:00',
      patient: {
        name: 'João Silva',
        photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Consultation standard',
      duration: 30,
      status: 'confirmed',
    },
    {
      id: '2',
      time: '09:45',
      patient: {
        name: 'Ana Costa',
        photo: 'https://images.pexels.com/photos/3765114/pexels-photo-3765114.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Téléconsultation',
      duration: 20,
      status: 'confirmed',
    },
    {
      id: '3',
      time: '10:30',
      patient: {
        name: 'Carlos Mendes',
        photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Consultation standard',
      duration: 30,
      status: 'confirmed',
    },
    {
      id: '4',
      time: '11:15',
      patient: {
        name: 'Sofia Rodrigues',
        photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Examen complet',
      duration: 60,
      status: 'pending',
    },
    {
      id: '5',
      time: '14:00',
      patient: {
        name: 'Miguel Ferreira',
        photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Consultation standard',
      duration: 30,
      status: 'confirmed',
    },
    {
      id: '6',
      time: '15:00',
      patient: {
        name: 'Beatriz Alves',
        photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Téléconsultation',
      duration: 20,
      status: 'confirmed',
    },
    {
      id: '7',
      time: '16:00',
      patient: {
        name: 'Ricardo Lopes',
        photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Consultation standard',
      duration: 30,
      status: 'confirmed',
    },
    {
      id: '8',
      time: '17:00',
      patient: {
        name: 'Isabel Martins',
        photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      },
      type: 'Consultation standard',
      duration: 30,
      status: 'confirmed',
    },
  ],
  appointmentsEvolution: [
    { date: '01/10', appointments: 18 },
    { date: '02/10', appointments: 22 },
    { date: '03/10', appointments: 15 },
    { date: '04/10', appointments: 20 },
    { date: '05/10', appointments: 19 },
    { date: '06/10', appointments: 0 },
    { date: '07/10', appointments: 0 },
    { date: '08/10', appointments: 25 },
    { date: '09/10', appointments: 23 },
    { date: '10/10', appointments: 21 },
    { date: '11/10', appointments: 24 },
    { date: '12/10', appointments: 20 },
    { date: '13/10', appointments: 0 },
    { date: '14/10', appointments: 0 },
    { date: '15/10', appointments: 22 },
    { date: '16/10', appointments: 26 },
    { date: '17/10', appointments: 19 },
    { date: '18/10', appointments: 23 },
    { date: '19/10', appointments: 21 },
    { date: '20/10', appointments: 0 },
    { date: '21/10', appointments: 0 },
    { date: '22/10', appointments: 24 },
    { date: '23/10', appointments: 20 },
    { date: '24/10', appointments: 25 },
    { date: '25/10', appointments: 22 },
    { date: '26/10', appointments: 23 },
    { date: '27/10', appointments: 0 },
    { date: '28/10', appointments: 0 },
    { date: '29/10', appointments: 21 },
    { date: '30/10', appointments: 24 },
  ],
  notifications: [
    {
      id: '1',
      type: 'appointment',
      message: 'Nouveau rendez-vous demandé par João Silva',
      time: '2025-10-04T09:30:00',
      read: false,
    },
    {
      id: '2',
      type: 'cancellation',
      message: 'Ana Costa a annulé son rendez-vous du 06/10',
      time: '2025-10-03T16:45:00',
      read: false,
    },
    {
      id: '3',
      type: 'payment',
      message: 'Paiement reçu de Carlos Mendes - 50€',
      time: '2025-10-03T14:20:00',
      read: true,
    },
  ],
  aiSuggestions: [
    {
      id: '1',
      type: 'optimization',
      message: 'Vous avez des créneaux vides le mercredi après-midi. Ouvrir ces horaires pourrait augmenter vos revenus de 15%.',
      priority: 'medium',
    },
    {
      id: '2',
      type: 'reminder',
      message: '3 patients n\'ont pas pris de rendez-vous depuis plus de 6 mois. Envoi automatique de rappel recommandé.',
      priority: 'low',
    },
  ],
  patients: [
    {
      id: '1',
      name: 'João Silva',
      email: 'joao.silva@email.com',
      phone: '+351 912 345 678',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-20',
      totalAppointments: 12,
      status: 'active',
    },
    {
      id: '2',
      name: 'Ana Costa',
      email: 'ana.costa@email.com',
      phone: '+351 913 456 789',
      photo: 'https://images.pexels.com/photos/3765114/pexels-photo-3765114.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-25',
      totalAppointments: 8,
      status: 'active',
    },
    {
      id: '3',
      name: 'Carlos Mendes',
      email: 'carlos.mendes@email.com',
      phone: '+351 914 567 890',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-10-01',
      totalAppointments: 15,
      status: 'active',
    },
    {
      id: '4',
      name: 'Sofia Rodrigues',
      email: 'sofia.rodrigues@email.com',
      phone: '+351 915 678 901',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-08-15',
      totalAppointments: 5,
      status: 'active',
    },
    {
      id: '5',
      name: 'Miguel Ferreira',
      email: 'miguel.ferreira@email.com',
      phone: '+351 916 789 012',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-30',
      totalAppointments: 10,
      status: 'active',
    },
    {
      id: '6',
      name: 'Beatriz Alves',
      email: 'beatriz.alves@email.com',
      phone: '+351 917 890 123',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-28',
      totalAppointments: 7,
      status: 'active',
    },
    {
      id: '7',
      name: 'Ricardo Lopes',
      email: 'ricardo.lopes@email.com',
      phone: '+351 918 901 234',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-15',
      totalAppointments: 6,
      status: 'active',
    },
    {
      id: '8',
      name: 'Isabel Martins',
      email: 'isabel.martins@email.com',
      phone: '+351 919 012 345',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-10-02',
      totalAppointments: 9,
      status: 'active',
    },
    {
      id: '9',
      name: 'Pedro Sousa',
      email: 'pedro.sousa@email.com',
      phone: '+351 920 123 456',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-07-10',
      totalAppointments: 4,
      status: 'inactive',
    },
    {
      id: '10',
      name: 'Catarina Lima',
      email: 'catarina.lima@email.com',
      phone: '+351 921 234 567',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-18',
      totalAppointments: 11,
      status: 'active',
    },
    {
      id: '11',
      name: 'André Torres',
      email: 'andre.torres@email.com',
      phone: '+351 922 345 678',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-22',
      totalAppointments: 13,
      status: 'active',
    },
    {
      id: '12',
      name: 'Mariana Pereira',
      email: 'mariana.pereira@email.com',
      phone: '+351 923 456 789',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-08-30',
      totalAppointments: 6,
      status: 'active',
    },
    {
      id: '13',
      name: 'Tiago Nunes',
      email: 'tiago.nunes@email.com',
      phone: '+351 924 567 890',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-12',
      totalAppointments: 8,
      status: 'active',
    },
    {
      id: '14',
      name: 'Luisa Santos',
      email: 'luisa.santos@email.com',
      phone: '+351 925 678 901',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-10-03',
      totalAppointments: 14,
      status: 'active',
    },
    {
      id: '15',
      name: 'Diogo Carvalho',
      email: 'diogo.carvalho@email.com',
      phone: '+351 926 789 012',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-08',
      totalAppointments: 5,
      status: 'active',
    },
    {
      id: '16',
      name: 'Teresa Vieira',
      email: 'teresa.vieira@email.com',
      phone: '+351 927 890 123',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-06-20',
      totalAppointments: 3,
      status: 'inactive',
    },
    {
      id: '17',
      name: 'Rui Oliveira',
      email: 'rui.oliveira@email.com',
      phone: '+351 928 901 234',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-27',
      totalAppointments: 10,
      status: 'active',
    },
    {
      id: '18',
      name: 'Paula Ribeiro',
      email: 'paula.ribeiro@email.com',
      phone: '+351 929 012 345',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-19',
      totalAppointments: 7,
      status: 'active',
    },
    {
      id: '19',
      name: 'Gonçalo Dias',
      email: 'goncalo.dias@email.com',
      phone: '+351 930 123 456',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-29',
      totalAppointments: 12,
      status: 'active',
    },
    {
      id: '20',
      name: 'Francisca Cunha',
      email: 'francisca.cunha@email.com',
      phone: '+351 931 234 567',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-08-25',
      totalAppointments: 6,
      status: 'active',
    },
    {
      id: '21',
      name: 'Vasco Pinto',
      email: 'vasco.pinto@email.com',
      phone: '+351 932 345 678',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-14',
      totalAppointments: 9,
      status: 'active',
    },
    {
      id: '22',
      name: 'Sara Monteiro',
      email: 'sara.monteiro@email.com',
      phone: '+351 933 456 789',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-10-01',
      totalAppointments: 11,
      status: 'active',
    },
    {
      id: '23',
      name: 'Bruno Fonseca',
      email: 'bruno.fonseca@email.com',
      phone: '+351 934 567 890',
      photo: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-07-05',
      totalAppointments: 4,
      status: 'inactive',
    },
    {
      id: '24',
      name: 'Helena Costa',
      email: 'helena.costa@email.com',
      phone: '+351 935 678 901',
      photo: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-26',
      totalAppointments: 8,
      status: 'active',
    },
    {
      id: '25',
      name: 'Nuno Gomes',
      email: 'nuno.gomes@email.com',
      phone: '+351 936 789 012',
      photo: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
      lastVisit: '2025-09-24',
      totalAppointments: 13,
      status: 'active',
    },
  ],
  services: [
    {
      id: '1',
      name: 'Consultation standard',
      duration: 30,
      price: 50,
      mode: ['Présentiel'],
      active: true,
      description: 'Consultation médicale générale',
    },
    {
      id: '2',
      name: 'Téléconsultation',
      duration: 20,
      price: 35,
      mode: ['En ligne'],
      active: true,
      description: 'Consultation à distance par vidéo',
    },
    {
      id: '3',
      name: 'Examen complet',
      duration: 60,
      price: 80,
      mode: ['Présentiel'],
      active: true,
      description: 'Bilan de santé complet avec examens',
    },
  ],
  statistics: {
    appointmentsByType: [
      { name: 'Consultation standard', value: 65 },
      { name: 'Téléconsultation', value: 30 },
      { name: 'Examen complet', value: 25 },
    ],
    attendanceRate: [
      { status: 'Présent', value: 92 },
      { status: 'Absent', value: 8 },
    ],
    monthlyRevenue: [
      { month: 'Avr', revenue: 4800 },
      { month: 'Mai', revenue: 5200 },
      { month: 'Juin', revenue: 4900 },
      { month: 'Juil', revenue: 5100 },
      { month: 'Août', revenue: 3800 },
      { month: 'Sept', revenue: 5500 },
      { month: 'Oct', revenue: 5400 },
    ],
  },
  payments: [
    {
      id: '1',
      date: '2025-10-03',
      patient: 'João Silva',
      amount: 50,
      status: 'paid',
      method: 'Carte bancaire',
    },
    {
      id: '2',
      date: '2025-10-03',
      patient: 'Ana Costa',
      amount: 35,
      status: 'paid',
      method: 'MB Way',
    },
    {
      id: '3',
      date: '2025-10-02',
      patient: 'Carlos Mendes',
      amount: 50,
      status: 'paid',
      method: 'Espèces',
    },
    {
      id: '4',
      date: '2025-10-02',
      patient: 'Sofia Rodrigues',
      amount: 80,
      status: 'pending',
      method: 'Virement',
    },
    {
      id: '5',
      date: '2025-10-01',
      patient: 'Miguel Ferreira',
      amount: 50,
      status: 'paid',
      method: 'Carte bancaire',
    },
    {
      id: '6',
      date: '2025-10-01',
      patient: 'Beatriz Alves',
      amount: 35,
      status: 'paid',
      method: 'MB Way',
    },
    {
      id: '7',
      date: '2025-09-30',
      patient: 'Ricardo Lopes',
      amount: 50,
      status: 'paid',
      method: 'Carte bancaire',
    },
    {
      id: '8',
      date: '2025-09-30',
      patient: 'Isabel Martins',
      amount: 50,
      status: 'paid',
      method: 'Espèces',
    },
    {
      id: '9',
      date: '2025-09-29',
      patient: 'Catarina Lima',
      amount: 50,
      status: 'paid',
      method: 'MB Way',
    },
    {
      id: '10',
      date: '2025-09-29',
      patient: 'André Torres',
      amount: 80,
      status: 'paid',
      method: 'Carte bancaire',
    },
  ],
  calendarEvents: [
    {
      id: '1',
      title: 'João Silva - Consultation',
      start: '2025-10-04T09:00:00',
      end: '2025-10-04T09:30:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '2',
      title: 'Ana Costa - Téléconsultation',
      start: '2025-10-04T09:45:00',
      end: '2025-10-04T10:05:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '3',
      title: 'Carlos Mendes - Consultation',
      start: '2025-10-04T10:30:00',
      end: '2025-10-04T11:00:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '4',
      title: 'Sofia Rodrigues - Examen complet',
      start: '2025-10-04T11:15:00',
      end: '2025-10-04T12:15:00',
      type: 'appointment',
      status: 'pending',
    },
    {
      id: '5',
      title: 'Pause déjeuner',
      start: '2025-10-04T12:30:00',
      end: '2025-10-04T14:00:00',
      type: 'break',
    },
    {
      id: '6',
      title: 'Miguel Ferreira - Consultation',
      start: '2025-10-04T14:00:00',
      end: '2025-10-04T14:30:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '7',
      title: 'Créneaux disponibles',
      start: '2025-10-04T14:30:00',
      end: '2025-10-04T15:00:00',
      type: 'available',
    },
    {
      id: '8',
      title: 'Beatriz Alves - Téléconsultation',
      start: '2025-10-04T15:00:00',
      end: '2025-10-04T15:20:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '9',
      title: 'Créneaux disponibles',
      start: '2025-10-04T15:20:00',
      end: '2025-10-04T16:00:00',
      type: 'available',
    },
    {
      id: '10',
      title: 'Ricardo Lopes - Consultation',
      start: '2025-10-04T16:00:00',
      end: '2025-10-04T16:30:00',
      type: 'appointment',
      status: 'confirmed',
    },
    {
      id: '11',
      title: 'Créneaux disponibles',
      start: '2025-10-04T16:30:00',
      end: '2025-10-04T17:00:00',
      type: 'available',
    },
    {
      id: '12',
      title: 'Isabel Martins - Consultation',
      start: '2025-10-04T17:00:00',
      end: '2025-10-04T17:30:00',
      type: 'appointment',
      status: 'confirmed',
    },
  ],
};

export const fakeAdminData = {
  kpis: {
    totalUsers: 1250,
    totalProfessionals: 87,
    validatedProfessionals: 75,
    pendingProfessionals: 12,
    appointmentsThisMonth: 3450,
    growthRate: 12.5,
    openTickets: 15,
  },
  registrationsByDay: [
    { date: '04/09', users: 12, professionals: 2 },
    { date: '05/09', users: 15, professionals: 1 },
    { date: '06/09', users: 18, professionals: 3 },
    { date: '07/09', users: 10, professionals: 1 },
    { date: '08/09', users: 14, professionals: 2 },
    { date: '09/09', users: 8, professionals: 0 },
    { date: '10/09', users: 9, professionals: 1 },
    { date: '11/09', users: 16, professionals: 2 },
    { date: '12/09', users: 19, professionals: 3 },
    { date: '13/09', users: 13, professionals: 1 },
    { date: '14/09', users: 11, professionals: 2 },
    { date: '15/09', users: 7, professionals: 0 },
    { date: '16/09', users: 10, professionals: 1 },
    { date: '17/09', users: 15, professionals: 2 },
    { date: '18/09', users: 17, professionals: 3 },
    { date: '19/09', users: 14, professionals: 1 },
    { date: '20/09', users: 12, professionals: 2 },
    { date: '21/09', users: 16, professionals: 1 },
    { date: '22/09', users: 9, professionals: 0 },
    { date: '23/09', users: 11, professionals: 1 },
    { date: '24/09', users: 18, professionals: 3 },
    { date: '25/09', users: 20, professionals: 2 },
    { date: '26/09', users: 15, professionals: 1 },
    { date: '27/09', users: 13, professionals: 2 },
    { date: '28/09', users: 17, professionals: 3 },
    { date: '29/09', users: 10, professionals: 0 },
    { date: '30/09', users: 12, professionals: 1 },
    { date: '01/10', users: 19, professionals: 2 },
    { date: '02/10', users: 21, professionals: 3 },
    { date: '03/10', users: 16, professionals: 2 },
  ],
  appointmentsBySpecialty: [
    { specialty: 'Médecine Générale', appointments: 520, percentage: 15.1 },
    { specialty: 'Cardiologie', appointments: 380, percentage: 11.0 },
    { specialty: 'Dentiste', appointments: 450, percentage: 13.0 },
    { specialty: 'Dermatologie', appointments: 290, percentage: 8.4 },
    { specialty: 'Pédiatrie', appointments: 340, percentage: 9.9 },
    { specialty: 'Psychiatrie', appointments: 310, percentage: 9.0 },
    { specialty: 'Gynécologie', appointments: 280, percentage: 8.1 },
    { specialty: 'Kinésithérapie', appointments: 265, percentage: 7.7 },
    { specialty: 'Ophtalmologie', appointments: 235, percentage: 6.8 },
    { specialty: 'Autres', appointments: 380, percentage: 11.0 },
  ],
  topCities: [
    { city: 'Lisbonne', users: 420, professionals: 35 },
    { city: 'Porto', users: 310, professionals: 22 },
    { city: 'Braga', users: 165, professionals: 12 },
    { city: 'Coimbra', users: 145, professionals: 9 },
    { city: 'Faro', users: 120, professionals: 7 },
  ],
  recentActivity: [
    {
      id: '1',
      type: 'user_registration',
      user: 'Miguel Costa',
      timestamp: '2025-10-04T09:45:00',
      details: 'Nouvel utilisateur inscrit',
    },
    {
      id: '2',
      type: 'professional_registration',
      user: 'Dr. Ana Martins',
      timestamp: '2025-10-04T09:30:00',
      details: 'Nouveau professionnel en attente de validation',
    },
    {
      id: '3',
      type: 'appointment',
      user: 'Sofia Rodrigues',
      timestamp: '2025-10-04T09:15:00',
      details: 'Rendez-vous créé avec Dr. Silva',
    },
    {
      id: '4',
      type: 'report',
      user: 'João Alves',
      timestamp: '2025-10-04T08:50:00',
      details: 'Signalement pour contenu inapproprié',
    },
    {
      id: '5',
      type: 'user_registration',
      user: 'Beatriz Santos',
      timestamp: '2025-10-04T08:30:00',
      details: 'Nouvel utilisateur inscrit',
    },
  ],
  users: Array.from({ length: 50 }, (_, i) => {
    const firstNames = ['João', 'Maria', 'Ana', 'Pedro', 'Sofia', 'Miguel', 'Beatriz', 'Ricardo', 'Catarina', 'André', 'Isabel', 'Tiago', 'Luisa', 'Carlos', 'Teresa'];
    const lastNames = ['Silva', 'Santos', 'Costa', 'Ferreira', 'Rodrigues', 'Alves', 'Martins', 'Oliveira', 'Pereira', 'Sousa', 'Lopes', 'Mendes', 'Dias', 'Cunha', 'Ribeiro'];
    const statuses = ['active', 'active', 'active', 'active', 'inactive', 'suspended'];
    const cities = ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Faro'];

    const firstName = firstNames[i % firstNames.length];
    const lastName = lastNames[Math.floor(i / firstNames.length) % lastNames.length];
    const status = statuses[i % statuses.length];
    const appointmentCount = Math.floor(Math.random() * 15) + 1;
    const daysAgo = Math.floor(Math.random() * 180);
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);

    return {
      id: `user-${i + 1}`,
      name: `${firstName} ${lastName}`,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${i}@email.com`,
      phone: `+351 9${10 + i} ${String(Math.floor(Math.random() * 1000)).padStart(3, '0')} ${String(Math.floor(Math.random() * 1000)).padStart(3, '0')}`,
      registrationDate: date.toISOString().split('T')[0],
      status,
      appointmentCount,
      city: cities[i % cities.length],
    };
  }),
  professionals: Array.from({ length: 30 }, (_, i) => {
    const firstNames = ['Dr. Maria', 'Dr. Pedro', 'Dr. Ana', 'Dr. Carlos', 'Dr. Sofia', 'Dr. Miguel', 'Dr. Isabel', 'Dr. Ricardo', 'Dr. Beatriz', 'Dr. João'];
    const lastNames = ['Santos', 'Costa', 'Silva', 'Ferreira', 'Rodrigues', 'Alves', 'Martins', 'Oliveira', 'Pereira', 'Sousa'];
    const specialties = ['Médecine Générale', 'Cardiologie', 'Dentiste', 'Dermatologie', 'Pédiatrie', 'Psychiatrie', 'Gynécologie', 'Kinésithérapie', 'Ophtalmologie', 'Orthopédie'];
    const statuses = i < 25 ? ['validated', 'validated', 'validated'][i % 3] : ['pending', 'rejected'][i % 2];
    const cities = ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Faro'];

    const firstName = firstNames[i % firstNames.length];
    const lastName = lastNames[Math.floor(i / firstNames.length) % lastNames.length];
    const specialty = specialties[i % specialties.length];
    const status = statuses;
    const appointmentCount = status === 'validated' ? Math.floor(Math.random() * 150) + 50 : 0;
    const cancellationRate = status === 'validated' ? Math.floor(Math.random() * 10) + 2 : 0;
    const daysAgo = Math.floor(Math.random() * 120);
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);

    return {
      id: `pro-${i + 1}`,
      name: `${firstName} ${lastName}`,
      email: `${firstName.toLowerCase().replace('. ', '.')}.${lastName.toLowerCase()}@cabinet.pt`,
      specialty,
      registrationNumber: `OM-${40000 + i}`,
      registrationDate: date.toISOString().split('T')[0],
      status,
      documentsVerified: status === 'validated',
      appointmentCount,
      cancellationRate,
      city: cities[i % cities.length],
    };
  }),
  allAppointments: Array.from({ length: 50 }, (_, i) => {
    const statuses = ['confirmed', 'confirmed', 'confirmed', 'completed', 'completed', 'cancelled', 'pending'];
    const specialties = ['Médecine Générale', 'Cardiologie', 'Dentiste', 'Dermatologie', 'Pédiatrie', 'Psychiatrie', 'Gynécologie', 'Kinésithérapie', 'Ophtalmologie', 'Orthopédie'];
    const cities = ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Faro'];
    const types = ['Présentiel', 'Présentiel', 'En ligne'];

    const daysOffset = i < 20 ? Math.floor(Math.random() * 30) + 1 : -Math.floor(Math.random() * 30);
    const date = new Date();
    date.setDate(date.getDate() + daysOffset);

    return {
      id: `apt-${i + 1}`,
      date: date.toISOString().split('T')[0],
      time: `${8 + Math.floor(Math.random() * 9)}:${['00', '30'][Math.floor(Math.random() * 2)]}`,
      patient: `Patient ${i + 1}`,
      professional: `Dr. ${i % 2 === 0 ? 'Silva' : 'Costa'}`,
      specialty: specialties[i % specialties.length],
      city: cities[i % cities.length],
      type: types[i % types.length],
      status: statuses[i % statuses.length],
    };
  }),
  appointmentStats: {
    totalAppointments: 3450,
    cancellationRate: 8.5,
    popularHours: [
      { hour: '09:00-10:00', count: 420 },
      { hour: '10:00-11:00', count: 480 },
      { hour: '11:00-12:00', count: 390 },
      { hour: '14:00-15:00', count: 440 },
      { hour: '15:00-16:00', count: 410 },
      { hour: '16:00-17:00', count: 380 },
    ],
  },
  faqItems: [
    {
      id: '1',
      questionFR: 'Comment prendre rendez-vous ?',
      answerFR: 'Recherchez un professionnel, consultez ses disponibilités et réservez en ligne.',
      questionPT: 'Como marcar uma consulta?',
      answerPT: 'Procure um profissional, consulte as suas disponibilidades e reserve online.',
      category: 'Général',
      active: true,
    },
    {
      id: '2',
      questionFR: 'Comment annuler un rendez-vous ?',
      answerFR: 'Accédez à "Mes rendez-vous" et cliquez sur "Annuler". L\'annulation doit être faite au moins 24h à l\'avance.',
      questionPT: 'Como cancelar uma consulta?',
      answerPT: 'Aceda a "As minhas consultas" e clique em "Cancelar". O cancelamento deve ser feito com pelo menos 24h de antecedência.',
      category: 'Rendez-vous',
      active: true,
    },
    {
      id: '3',
      questionFR: 'Quels sont les modes de paiement acceptés ?',
      answerFR: 'Carte bancaire, MB Way, virement bancaire et espèces (en cabinet uniquement).',
      questionPT: 'Quais os métodos de pagamento aceites?',
      answerPT: 'Cartão bancário, MB Way, transferência bancária e dinheiro (apenas no consultório).',
      category: 'Paiement',
      active: true,
    },
  ],
  supportTickets: [
    {
      id: 'ticket-1',
      user: 'João Silva',
      userType: 'patient',
      subject: 'Problème de connexion',
      status: 'open',
      priority: 'medium',
      createdAt: '2025-10-03T14:30:00',
      lastUpdate: '2025-10-03T14:30:00',
      messages: 3,
    },
    {
      id: 'ticket-2',
      user: 'Dr. Maria Santos',
      userType: 'professional',
      subject: 'Validation de documents',
      status: 'in_progress',
      priority: 'high',
      createdAt: '2025-10-02T10:15:00',
      lastUpdate: '2025-10-03T09:20:00',
      messages: 5,
    },
    {
      id: 'ticket-3',
      user: 'Ana Costa',
      userType: 'patient',
      subject: 'Remboursement rendez-vous annulé',
      status: 'open',
      priority: 'high',
      createdAt: '2025-10-01T16:45:00',
      lastUpdate: '2025-10-01T16:45:00',
      messages: 1,
    },
    {
      id: 'ticket-4',
      user: 'Carlos Mendes',
      userType: 'patient',
      subject: 'Modification de profil impossible',
      status: 'resolved',
      priority: 'low',
      createdAt: '2025-09-28T11:20:00',
      lastUpdate: '2025-09-30T14:10:00',
      messages: 4,
    },
    {
      id: 'ticket-5',
      user: 'Dr. Pedro Costa',
      userType: 'professional',
      subject: 'Question sur les paiements',
      status: 'in_progress',
      priority: 'medium',
      createdAt: '2025-09-30T09:00:00',
      lastUpdate: '2025-10-02T15:30:00',
      messages: 6,
    },
    {
      id: 'ticket-6',
      user: 'Sofia Rodrigues',
      userType: 'patient',
      subject: 'Document non reçu',
      status: 'open',
      priority: 'medium',
      createdAt: '2025-10-03T08:15:00',
      lastUpdate: '2025-10-03T08:15:00',
      messages: 1,
    },
    {
      id: 'ticket-7',
      user: 'Miguel Ferreira',
      userType: 'patient',
      subject: 'Question sur la téléconsultation',
      status: 'resolved',
      priority: 'low',
      createdAt: '2025-09-27T13:40:00',
      lastUpdate: '2025-09-28T10:20:00',
      messages: 3,
    },
    {
      id: 'ticket-8',
      user: 'Dr. Ana Ferreira',
      userType: 'professional',
      subject: 'Modification horaires indisponible',
      status: 'open',
      priority: 'high',
      createdAt: '2025-10-04T07:30:00',
      lastUpdate: '2025-10-04T07:30:00',
      messages: 1,
    },
  ],
  systemSettings: {
    general: {
      platformName: 'MediConnect',
      logo: 'https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=200',
      primaryColor: '#3B82F6',
      secondaryColor: '#10B981',
      supportEmail: 'support@mediconnect.pt',
      contactEmail: 'contact@mediconnect.pt',
      activeLanguages: ['FR', 'PT'],
    },
    payment: {
      acceptedMethods: ['Carte bancaire', 'MB Way', 'Virement', 'Espèces'],
      platformCommission: 12,
      currency: 'EUR',
    },
  },
};
